env:
  browser: true
  es2021: true
settings:
  react:
    version: detect
extends:
  - plugin:react/recommended
  - "eslint:recommended"
overrides:
  - extends:
      - xo-typescript
    files:
      - '*.ts'
      - '*.tsx'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {
  '@typescript-eslint/object-curly-spacing': off,
  '@typescript-eslint/prefer-nullish-coalescing': off
}
